generatorName: python
outputDir: samples/openapi3/client/petstore/python_aws_sigv4
inputSpec: modules/openapi-json-schema-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-aws-sigv4.yaml
templateDir: modules/openapi-json-schema-generator/src/main/resources/python
additionalProperties:
  packageName: petstore_api
  recursionLimit: "1234"
